FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app
COPY requirements/ /app/requirements/
RUN pip install --upgrade pip && \
    pip install -r requirements/requirements-stable.txt -c requirements/constraints/3.11.txt

COPY . /app

CMD ["bash"]
