name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        channel: ["stable", "candidate"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps (${{ matrix.channel }})
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-${{ matrix.channel }}.txt -c requirements/constraints/${{ matrix.python-version }}.txt
      - name: Lint
        run: |
          black --check .
          isort --check-only .
          flake8 .
      - name: Type check
        run: |
          mypy qraft
      - name: Dependency audit
        run: |
          python -m pip install pip-audit
          pip-audit --strict
      - name: Test
        run: |
          pytest --cov=qraft --cov-report=term-missing --cov-fail-under=80
